"""
A.V.I. LiveKit desktop voice client.

This process does NOT synthesize speech locally. It joins the A.V.I.
LiveKit room, sends text to the agent, and plays the remote audio track
generated by Inworld/Priya.
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
import queue
import threading
import uuid
from datetime import timedelta

import sounddevice as sd
from dotenv import load_dotenv
from livekit import api, rtc
from livekit.api import AgentDispatch, CreateAgentDispatchRequest  # noqa: F401

load_dotenv()


# --------------------------------------------------------------------
# Quiet down the harmless "Event loop is closed" spam.
# --------------------------------------------------------------------

class _LivekitShutdownFilter(logging.Filter):
    def filter(self, record: logging.LogRecord) -> bool:  # noqa: D401
        try:
            msg = record.getMessage() or ""
        except Exception:
            return True
        if "error putting to queue" in msg and "Event loop is closed" in msg:
            return False
        return True


_livekit_logger = logging.getLogger("livekit")
_livekit_logger.addFilter(_LivekitShutdownFilter())

LIVEKIT_URL = os.getenv("LIVEKIT_URL", "").strip()
LIVEKIT_API_KEY = os.getenv("LIVEKIT_API_KEY", "").strip()
LIVEKIT_API_SECRET = os.getenv("LIVEKIT_API_SECRET", "").strip()
ROOM_NAME = f"{os.getenv('LIVEKIT_ROOM', 'avi-room').strip() or 'avi-room'}-{uuid.uuid4().hex[:6]}"
LIVEKIT_AGENT_NAME = os.getenv("LIVEKIT_AGENT_NAME", "avi").strip() or "avi"


class AVILiveKitClient:
    def __init__(self):
        self.room: rtc.Room | None = None
        self.platform_audio = None
        self.audio_source = None
        self.audio_track = None
        self._audio_owner = None

        self.loop: asyncio.AbstractEventLoop | None = None
        self.thread: threading.Thread | None = None

        self.connected = False
        self.voice_ready = False
        self.voice_ready_event = threading.Event()
        self.speaking = False
        self.speaking_event = threading.Event()

        self.playback_stream = None
        self.playback_queue: queue.Queue[bytes] = queue.Queue()
        self.playback_thread: threading.Thread | None = None
        self.playback_running = False

        self.last_error = ""

    @property
    def ready(self) -> bool:
        return self.connected and self.voice_ready

    def _validate_config(self):
        missing = []
        if not LIVEKIT_URL:
            missing.append("LIVEKIT_URL")
        if not LIVEKIT_API_KEY:
            missing.append("LIVEKIT_API_KEY")
        if not LIVEKIT_API_SECRET:
            missing.append("LIVEKIT_API_SECRET")
        if missing:
            raise RuntimeError(
                "LiveKit credentials are missing: " + ", ".join(missing) +
                ". Add them to the project's .env file."
            )

    def create_token(self):
        self._validate_config()
        identity = f"avi-desktop-{uuid.uuid4().hex[:8]}"
        return (
            api.AccessToken(LIVEKIT_API_KEY, LIVEKIT_API_SECRET)
            .with_identity(identity)
            .with_name("A.V.I Desktop")
            .with_grants(
                api.VideoGrants(
                    room_join=True,
                    room=ROOM_NAME,
                    can_publish=True,
                    can_subscribe=True,
                    can_publish_data=True,
                )
            )
            .with_ttl(timedelta(hours=6))
            .to_jwt()
        )

    # --------------------------- playback ---------------------------

    def _start_playback(self, sample_rate=48000, channels=1):
        if self.playback_stream:
            return

        print(f"[A.V.I] Starting remote audio playback {sample_rate}Hz / {channels}ch")
        self.playback_running = True

        try:
            self.playback_stream = sd.RawOutputStream(
                samplerate=sample_rate,
                channels=channels,
                dtype="int16",
                blocksize=0,
            )
            self.playback_stream.start()
        except Exception as exc:
            self.last_error = str(exc)
            self.playback_stream = None
            print(f"[A.V.I] Playback initialization error: {exc}")

    def _stop_playback(self):
        self.playback_running = False
        if self.playback_stream:
            try:
                self.playback_stream.stop()
            except Exception:
                pass
            try:
                self.playback_stream.close()
            except Exception:
                pass
            self.playback_stream = None

        while True:
            try:
                self.playback_queue.get_nowait()
            except queue.Empty:
                break

    def _playback_worker(self):
        while self.playback_running:
            try:
                audio_data = self.playback_queue.get(timeout=0.2)
            except queue.Empty:
                continue

            if self.playback_stream:
                try:
                    self.playback_stream.write(audio_data)
                except Exception as exc:
                    print(f"[A.V.I] Audio playback error: {exc}")

    # ------------------------- remote audio -------------------------

    async def _receive_audio(self, track, participant):
        print(f"[A.V.I] Receiving Priya audio from {participant.identity}")
        try:
            audio_stream = rtc.AudioStream(
                track=track,
                sample_rate=48000,
                num_channels=1,
            )

            async for event in audio_stream:
                frame = event.frame

                # Single thread / single stream initialization check
                if not self.playback_stream:
                    self._start_playback(
                        frame.sample_rate,
                        frame.num_channels,
                    )

                if self.playback_thread is None or not self.playback_thread.is_alive():
                    self.playback_thread = threading.Thread(
                        target=self._playback_worker,
                        daemon=True,
                    )
                    self.playback_thread.start()

                self.playback_queue.put(bytes(frame.data))
        except Exception as exc:
            print(f"[A.V.I] Remote Priya audio error: {exc}")

    # ----------------------------- room -----------------------------

    async def connect_async(self):
        self._validate_config()
        print("[A.V.I] Connecting desktop voice client to LiveKit...")
        self.room = rtc.Room()

        @self.room.on("participant_connected")
        def participant_connected(participant):
            print(f"[A.V.I] Participant connected: {participant.identity}")

        @self.room.on("participant_disconnected")
        def participant_disconnected(participant):
            print(f"[A.V.I] Participant disconnected: {participant.identity}")
            if participant.identity == self._audio_owner:
                self._audio_owner = None
            if participant.identity != getattr(self.room.local_participant, "identity", None):
                self.voice_ready = False
                self.voice_ready_event.clear()

        @self.room.on("track_subscribed")
        def track_subscribed(track, publication, participant):
            print(f"[A.V.I] Track received from {participant.identity}: {track.kind}")
            if track.kind != rtc.TrackKind.KIND_AUDIO or not self.loop:
                return

            # Single audio owner lock to prevent double audio playback
            if self._audio_owner and self._audio_owner != participant.identity:
                print(f"[A.V.I] Ignoring duplicate agent audio from {participant.identity}")
                return

            self._audio_owner = participant.identity
            self.loop.create_task(self._receive_audio(track, participant))

        @self.room.on("data_received")
        def data_received(packet: rtc.DataPacket):
            if packet.topic == "avi.speech_start":
                self.speaking = True
                self.speaking_event.set()
                print("[A.V.I] Priya started speaking; microphone input paused.")
                return

            if packet.topic == "avi.speech_end":
                self.speaking = False
                self.speaking_event.clear()
                print("[A.V.I] Priya finished speaking; microphone input resumed.")
                return

            if packet.topic != "avi.ready":
                return
            try:
                payload = json.loads(packet.data.decode("utf-8"))
                if payload.get("status") == "ready":
                    self.voice_ready = True
                    self.voice_ready_event.set()
                    print(
                        "[A.V.I] Priya TTS READY "
                        f"({payload.get('tts', 'Inworld')})."
                    )
            except Exception as exc:
                print(f"[A.V.I] Ready packet error: {exc}")

        @self.room.on("disconnected")
        def disconnected(reason):
            print(f"[A.V.I] LiveKit disconnected: {reason}")
            self.connected = False
            self.voice_ready = False
            self.voice_ready_event.clear()

        token = self.create_token()
        await self.room.connect(LIVEKIT_URL, token)

        print(f"[A.V.I] Connected to room: {ROOM_NAME}")

        try:
            lk_api = api.LiveKitAPI(
                LIVEKIT_URL,
                LIVEKIT_API_KEY,
                LIVEKIT_API_SECRET,
            )
            dispatch_req = CreateAgentDispatchRequest(
                room=ROOM_NAME,
                agent_name=LIVEKIT_AGENT_NAME,
            )
            await lk_api.agent_dispatch.create_dispatch(dispatch_req)
            print(
                f"[A.V.I] Dispatched agent '{LIVEKIT_AGENT_NAME}' "
                f"to room '{ROOM_NAME}'."
            )
            await lk_api.aclose()
        except Exception as exc:
            print(f"[A.V.I] Agent dispatch failed: {exc}")

        try:
            self.platform_audio = rtc.PlatformAudio()
            microphones = self.platform_audio.recording_devices()
            speakers = self.platform_audio.playout_devices()
            print(f"[A.V.I] Microphones detected: {len(microphones)}")
            print(f"[A.V.I] Speakers detected: {len(speakers)}")
            print("[A.V.I] Microphone NOT published (echo prevention).")
        except Exception as exc:
            print(f"[A.V.I] PlatformAudio probe skipped: {exc}")

        self.connected = True
        print("[A.V.I] Desktop LiveKit link ONLINE. Asking the agent for Priya TTS readiness...")

        try:
            await self.room.local_participant.publish_data(
                b"{}",
                reliable=True,
                topic="avi.hello",
            )
        except Exception as exc:
            print(f"[A.V.I] Could not request TTS readiness: {exc}")

        while self.connected:
            await asyncio.sleep(1)

    def _run_loop(self):
        self.loop = asyncio.new_event_loop()
        asyncio.set_event_loop(self.loop)
        try:
            self.loop.run_until_complete(self.connect_async())
        except Exception as exc:
            self.last_error = str(exc)
            self.connected = False
            self.voice_ready = False
            self.voice_ready_event.clear()
            print(f"[A.V.I] LiveKit connection ERROR: {exc}")
        finally:
            try:
                pending = asyncio.all_tasks(self.loop)
                for task in pending:
                    if task is asyncio.current_task(self.loop):
                        continue
                    try:
                        task.cancel()
                    except Exception:
                        pass
                if pending:
                    self.loop.run_until_complete(
                        asyncio.gather(*pending, return_exceptions=True)
                    )
            except Exception:
                pass
            try:
                self.loop.close()
            except Exception:
                pass
            self.loop = None

    def start(self):
        if self.thread and self.thread.is_alive():
            return

        self.last_error = ""
        self.voice_ready = False
        self.voice_ready_event.clear()

        self.thread = threading.Thread(
            target=self._run_loop,
            name="AVI-LiveKit",
            daemon=True,
        )
        self.thread.start()

    def wait_until_ready(self, timeout=45.0):
        self.start()
        deadline = __import__("time").monotonic() + timeout
        while __import__("time").monotonic() < deadline:
            if self.ready:
                return True
            if self.last_error:
                return False
            __import__("time").sleep(0.1)
        return False

    def speak(self, text, wait_for_ready=True):
        text = str(text or "").strip()
        if not text:
            return False

        if wait_for_ready and not self.wait_until_ready():
            print(
                "[A.V.I] Priya TTS is not ready. "
                f"{self.last_error or 'LiveKit agent did not become ready.'}"
            )
            return False

        if not self.ready or not self.room or not self.loop:
            print("[A.V.I] Cannot speak: Priya TTS is not ready.")
            return False

        payload = json.dumps({"text": text}).encode("utf-8")

        async def send():
            try:
                await self.room.local_participant.publish_data(
                    payload,
                    reliable=True,
                    topic="avi.speak",
                )
                print("[A.V.I] Speech request sent to Priya TTS.")
            except Exception as exc:
                print(f"[A.V.I] Speech request error: {exc}")

        try:
            asyncio.run_coroutine_threadsafe(send(), self.loop)
            return True
        except Exception as exc:
            print(f"[A.V.I] Could not send speech: {exc}")
            return False

    def wait_until_silent(self, timeout=30.0):
        return not self.speaking_event.wait(timeout=timeout)

    def stop(self):
        self.connected = False
        self.voice_ready = False
        self.voice_ready_event.clear()
        self.speaking = False
        self.speaking_event.clear()
        print("[A.V.I] Stopping LiveKit...")
        self._stop_playback()

        if self.loop:
            try:
                asyncio.run_coroutine_threadsafe(
                    self._disconnect_async(),
                    self.loop,
                )
            except Exception:
                pass

    async def _disconnect_async(self):
        try:
            if self.audio_track:
                try:
                    self.audio_track.stop()
                except Exception:
                    pass

            if self.audio_source:
                try:
                    self.audio_source.close()
                except Exception:
                    pass

            if self.room:
                try:
                    await self.room.disconnect()
                except Exception:
                    pass

            if self.platform_audio:
                try:
                    self.platform_audio.close()
                except Exception:
                    pass
        finally:
            self.connected = False
            self.voice_ready = False
            self.voice_ready_event.clear()
            print("[A.V.I] Voice link OFFLINE.")